language: python

python:
- "3.9"

env:
- DJANGO=4.2.6

install:
- pip install -r requirements.txt
- curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.exe -o coveralls.exe

script:
- black --check .
- flake8 . --max-line-length=99
- coverage run manage.py test
- coverage xml
- ./coveralls report --repo-token=$COVERALLTOKEN coverages.xml

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWSKEY"
  secret_access_key: "$AWSSECRET"
  region: "us-west-2"
  app: "django-tutorial-redo"
  env: "django-env6"
  bucket_name: "django-ebs-bucket"
  on:
    branch: main
