language: python

python:
- "3.9"

env:
- DJANGO=4.2.6

script:
- python manage.py test

deploy:
  -provider: elasticbeanstalk
  -access_key_id: 
    -secure:"$AWSKEY"
  -secret_access_key:
    -secure:"$AWSSECRET"
  -region:"us-west-2"
  -app:"django-tutorial-redo"
  -env:"django-env6"
