language: python

python:
- "3.9"

install:
- pip install -r requirements.txt
- curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz

script:
- black --check .
- flake8 . --max-line-length=99
- coverage run manage.py test
- coverage xml
- coveralls report --repo-token=$COVERALLTOKEN coverages.xml

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWSKEY"
  secret_access_key: "$AWSSECRET"
  region: "us-west-2"
  app: "django-tutorial-redo"
  env: "django-env6"
  bucket_name: "django-ebs-bucket"
  on:
    branch: main
